/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
/control/alias events 1000000
/run/printProgress 100000

/gps/ene/mono 2.5 MeV
/gps/particle neutron
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 1 mm
/gps/pos/centre 0 0 -1 cm
/gps/direction 0 0 1

/analysis/setFileName TOF
/run/beamOn {events}